<AccountSettings>:
    MDBoxLayout:
        orientation: "vertical"

        MDLabel:
            text: "Account settings"
            font_style: "Headline"
            halign: "center"

        MDButton:
            style: "tonal"
            pos_hint: {"center_x": 0.5}
            on_press:
                root.on_log_out()
                app.root.current = "signup_screen"

            MDButtonText:
                text: "Log out"
